
spring.datasource:
  url: jdbc:mysql://localhost:3306/db
  username: user
  password: password
  hikari.maximum-pool-size: 20

spring.jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  show-sql: true
  hibernate.ddl-auto: update

file:
  location:
    input: /home/ovi/development/test/orangetoolz-file-parsing/data/input/1M-customers.txt
    output:  /home/ovi/development/test/orangetoolz-file-parsing/data/output/

chunk.size:
    db.write: 10000
    file.write: 500000

thread.size.max: 10